### ISSUE TITLE
Transport for eAPI should not be restricted to HTTPS

### ISSUE THREAD

**Issue by narJH27** [napalm-automation/napalm-eos#64] opened 2016-10-10 19:43 UTC
### Description of Issue/Question

eAPI allows the use of UNIX Sockets, HTTP/HTTPS, and HTTP-Local as various transport options to access the device. It would be nice to have the .open() method take an argument specifying the preferred transport method rather than hardcoding `https` as the only possible mechanism.
### napalm-eos version

(Paste verbatim output from `pip freeze | grep napalm-eos` between quotes below)

```

```
### eOS version

(Paste verbatim output from `show version | json` between quotes below)

```

```
### Error Traceback

(Paste the complete traceback of the exception between quotes below)

```

```

**Comment by dbarrosop** [comment] 2016-10-11 08:38
I had been meaning to implement this for a while so now I got the perfect excuse : )

You should be able to use http or the socket transport like this:

```
eos_driver = get_network_driver('eos')
device = eos_driver('', '', '', optional_args{'eos_transport': 'socket'})
...
```

and 

```
eos_driver = get_network_driver('eos')
device = eos_driver('sw00', 'user', 'passwd', optional_args{'eos_transport': 'http'})
...
```

**Comment by narJH27** [comment] 2016-10-11 21:28
Will be great if this can be done the way you have mentioned :)

**Comment by dbarrosop** [comment] 2016-10-11 21:30
It's implemented already in #65, although it's not merged yet. Would be nice if you could pull the branch and give it a try.

**Comment by narJH27** [comment] 2016-11-07 19:10
@dbarrosop I tested the above patch that adds the functionality to use the `unix-socket` as a transport over `http/https`. However, the napalm open() method blows when I try to connect using unix sockets, but `pyeapi` connects just fine using the socket as a transport. Below are the excerpts of my tests:

```
>>> conn = EOSDriver('', '', '', optional_args={'eos_transport': 'socket'})
>>> 
>>> conn.open()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/napalm_eos/eos.py", line 84, in open
napalm_base.exceptions.ConnectionException: unable to connect to eAPI
>>> 
>>> 
>>> import pyeapi
>>> 
>>> conn2 = pyeapi.client.connect(transport='socket')
>>>
```

If you notice, using napalm, the open() blows on line 84, which indicates that `self.transport` is getting defaulting to http or https somehow. FYI, I am running this locally on the box.

Can you take a look at this please?

**Comment by dbarrosop** [comment] 2016-11-07 19:14
Looks like a bug, reopening.

**Comment by narJH27** [comment] 2016-11-07 19:15
Thanks @dbarrosop .

**Comment by dbarrosop** [comment] 2016-11-07 19:20
Mmm, can't reproduce the issue. Can you verify which version of `napalm-eos` you are using? The error you mention actually matches the error you would get if you were running an older version without support for this

**Comment by narJH27** [comment] 2016-11-07 19:57
I seem to have had an older version of `napalm-eos`. However, due to the typos in the code, the connection doesn't go through when `optional_args` has `eos_transport` specified.

**Comment by dbarrosop** [comment] 2016-11-07 20:07
0.4.3, which solves that issue, has just been released.

**Closed as completed** 2016-11-07 20:06 UTC
